language: rust

cache: cargo

matrix:
  include:
    - rust: stable
      os: osx
    - rust: nightly
      os: osx
    - rust: stable
      os: linux
      env: CRATES_IO_PUBLISH=true
    - rust: nightly
      os: linux

install: |
  if [ "$TRAVIS_RUST_VERSION" != nightly ]; then
    rustup component add clippy
  fi

script:
  - cargo test --doc
  - cargo test --examples
  - cargo test --lib --benches --tests
  - cargo test --lib --benches --tests --no-default-features
  - cargo test --lib --benches --tests --all-features
  - |
    if [ "$TRAVIS_RUST_VERSION" != nightly ]; then
      cargo clippy
    fi

deploy:
  provider: script
  script:
    - cargo publish --token "${CRATES_IO_TOKEN}"
  on:
    tags: true
    all_branches: true
    condition: $CRATES_IO_PUBLISH = true

notifications:
  email:
    on_success: never
